<?php 
/*
 * This file is part of CashOnDeliveryFee-v2.0.1.1.zip.
 *
 * (c) Rich Software <opencart@rich-software.eu>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart-extensions.net/order-totals/cod-fee for updates.
 */
?><?php
$_['text_cod_fee'] = 'COD Fee';