<?php 
/*
 * This file is part of CashOnDeliveryFee-v2.0.1.1.zip.
 *
 * (c) Rich Software <opencart@rich-software.eu>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart-extensions.net/order-totals/cod-fee for updates.
 */
?><?php
// Heading
$_['heading_title']    = 'COD Fee';

// Text
$_['text_total']       = 'Order Totals';
$_['text_success']     = 'Success: You have modified COD fee total!';
$_['text_edit']        = 'Edit COD Fee Total';

// Entry
$_['entry_total']      = 'Order Total';
$_['entry_fee']        = 'Fee';
$_['entry_tax_class']  = 'Tax Class';
$_['entry_status']     = 'Status';
$_['entry_sort_order'] = 'Sort Order';

// Help
$_['help_total']       = 'If the checkout total of the order reaches this amount the fee will not be applied any more.';
	$_['help_fee']       = 'If you put a \'%\' at the end, e.g. 10%, it will be a percentage, otherwise it will be a fixed fee.';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify COD fee total!';