<?php 
/*
 * This file is part of CashOnDeliveryFee-v2.0.1.1.zip.
 *
 * (c) Rich Software <opencart@rich-software.eu>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart-extensions.net/order-totals/cod-fee for updates.
 */
?><?php
class ModelTotalCodfee extends Model { public function getTotal(&$total_data, &$total, &$taxes) { if (((isset($this->session->data['payment_method']['code']) && ($this->session->data['payment_method']['code'] == 'cod')) && ($this->cart->getSubTotal() < $this->config->get('cod_fee_total'))) && ($this->cart->getSubTotal() > 0)) { $codFee = trim($this->config->get('cod_fee_fee')); $percent = FALSE; if (substr($codFee, -1) === '%') { $codFee = $this->cart->getSubTotal() * (substr($codFee, 0, -1) / 100); $percent = TRUE; } $this->load->language('total/cod_fee'); $total_data[] = array( 'code' => 'cod_fee', 'title' => ($percent ? $this->language->get('text_cod_fee') . ' (' . $this->config->get('cod_fee_fee') . ')' : $this->language->get('text_cod_fee')), 'value' => $codFee, 'sort_order' => $this->config->get('cod_fee_sort_order') ); if ($this->config->get('cod_fee_tax_class_id')) { $tax_rates = $this->tax->getRates($codFee, $this->config->get('cod_fee_tax_class_id')); foreach ($tax_rates as $tax_rate) { if (!isset($taxes[$tax_rate['tax_rate_id']])) { $taxes[$tax_rate['tax_rate_id']] = $tax_rate['amount']; } else { $taxes[$tax_rate['tax_rate_id']] += $tax_rate['amount']; } } } $total += $codFee; } } }